export const resources = {
    en: {
        translation: {
            welcome: 'Welcome',
            changeLanguage: 'Change Language',
            title: 'Health Examination',
            diagnoseDate: 'Diagnosis Date',
            dischargeSummary: 'Discharge Summary',
            cancel: 'Cancel',
            normalResult: 'Normal Result',
            abnormalResult: 'Abnormal Result',
            medicationName: 'Medication Name',
            viewDetails: 'View Details',
            normal: 'Normal',
            abnormal: 'Abnormal',
            consultation: 'Urgent Consultation',
            consultDirectly: 'Consult medical staff directly',
            unit: 'Unit',
            normalValue: 'Normal Value',
            fee: 'Fee',
            details: 'Details',
            contact: 'Contact',
            hotline: 'Hotline',
            aboutClinic: 'About the Clinic',
            additionalInfo: 'Additional Information',
            back: 'Back',
            examinationDetails: 'Examination Details',
            priceRange: 'Price Range',
            noData: 'No Data Available',

        },
    },
    th: {
        translation: {
            welcome: 'ยินดีต้อนรับ',
            changeLanguage: 'เปลี่ยนภาษา',
            title: 'ตรวจสุขภาพ',
            diagnoseDate: 'ตรวจวันที่',
            dischargeSummary: 'ใบสรุปผลตรวจ',
            cancel: 'ยกเลิก',
            normalResult: 'ผลตรวจปกติ',
            abnormalResult: 'ผลตรวจผิดปกติ',
            medicationName: 'ชื่อยา',
            viewDetails: 'ดูรายละเอียด',
            normal: 'ปกติ',
            abnormal: 'ผิดปกติ',
            consultation: 'ปรึกษาด่วน',
            consultDirectly: 'ปรึกษาบุคลากรทางการแพทย์ที่เกี่ยวข้องโดยตรง',
            unit: 'หน่วย',
            normalValue: 'ค่าปกติ',
            fee: 'ค่าธรรมเนียม',
            details: 'รายละเอียด',
            contact: 'ติดต่อ',
            hotline: 'สายด่วน',
            aboutClinic: 'เกี่ยวกับคลินิก',
            additionalInfo: 'ข้อมูลเพิ่มเติม',
            back: 'ย้อนกลับ',
            examinationDetails: 'รายละเอียดการตรวจ',
            priceRange: 'ช่วงราคา',
            noData: 'ไม่มีข้อมูล',

        },
    },
};
